[package]
name = "modbus"
version = "0.1.0"
authors = ["Chris Evans <cevans3326@gmail.com>"]

[dependencies]
libc = "*"
modbus-sys = { path = "modbus-sys", version = "*" }
errno = "*"
rand = "0.3"


[lib]
name = "modbus"
path = "src/lib.rs"
